version: '3.8'

services:
  frontend:
    container_name: cosmos-oddysey-frontend
    build:
      context: ./cosmos-oddysey-frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production

  backend:
    container_name: cosmos-oddysey-backend
    build:
      context: ./cosmos-oddysey-backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres
    ports:
      - '5432:5432' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql
      - POSTGRES_DB=CosmosOddyseyDatabase
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
